# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(db_column=b'faq_title', null=True, verbose_name=b'\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81')),
                ('answer', models.TextField(blank=True, db_column=b'faq_answer', null=True, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82')),
                ('date', models.DateField(db_column=b'faq_date', null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0')),
                ('lang', models.CharField(db_column=b'faq_lang', max_length=2, null=True)),
                ('position', models.IntegerField(blank=True, db_column=b'faq_position', default=0)),
            ],
            options={
                'ordering': ['position', 'pk'],
                'db_table': 'kase_faq',
            },
        ),
    ]
