# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['position', 'pk'], 'permissions': (('view_faq', 'Can view faq'),)},
        ),
    ]
