# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pk'], 'permissions': (('view_events', 'Can view events'),)},
        ),
    ]
