# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xa7\xd0\x9f\xd0\xa3'),
        ),
    ]
