# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_staticpage_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['idx', 'pk'], 'permissions': (('view_staticpage', 'Can view static pages'),)},
        ),
    ]
