# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiniCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fini_code', models.CharField(max_length=64, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [ru]')),
                ('name_en', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [en]')),
                ('name_kz', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [kz]')),
                ('unit_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xd0\x95\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 \xd0\xb8\xd0\xb7\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f [ru]')),
                ('unit_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xd0\x95\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 \xd0\xb8\xd0\xb7\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f [en]')),
                ('unit_kz', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xd0\x95\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 \xd0\xb8\xd0\xb7\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f [kz]')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [ru]')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [en]')),
                ('title_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [kz]')),
                ('isvisible', models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb7\xd0\xb8\xd1\x82\xd1\x8c')),
                ('fini_code_ind_ttl', models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd0\xb8 \xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0')),
                ('fini_code_diff_ttl', models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd0\xb8 \xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0')),
                ('fini_code_so', models.IntegerField(default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xb5 \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
                ('fini_code_chrt_type', models.CharField(blank=True, choices=[(b'linear', b'\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xb9\xd0\xbd\xd1\x8b\xd0\xb9'), (b'bar', b'\xd1\x81\xd1\x82\xd0\xbe\xd0\xbb\xd0\xb1\xd0\xb8\xd0\xba\xd0\xb8'), (b'arraychrt', b'array')], max_length=20, null=True, verbose_name=b'\xd0\x93\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xba \xd1\x82\xd0\xb8\xd0\xbf')),
                ('fini_code_chrt_pd', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x93\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xba \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbe\xd0\xb4')),
                ('fini_code_ind_frmt', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa0\xd0\xb0\xd0\xb7\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0')),
                ('fini_code_diff_frmt', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\xa0\xd0\xb0\xd0\xb7\xd1\x80\xd1\x8f\xd0\xb4\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0')),
                ('trandtype', models.CharField(blank=True, choices=[(b'normal', b'\xd0\xb2 \xd0\xb8\xd0\xb7\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb8 \xd0\xb7\xd0\xbd\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'), (b'percent', b'\xd0\xb2 \xd0\xbf\xd1\x80\xd0\xbe\xd1\x86\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x85')], max_length=20, null=True, verbose_name=b'\xd0\x92\xd1\x8b\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x82\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xa1\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('kase_info_key', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87')),
                ('value_divisor', models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\x94\xd0\xb5\xd0\xbb\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')),
            ],
            options={
                'ordering': ['fini_code_so', 'pk'],
                'db_table': 'fini_code',
            },
        ),
        migrations.CreateModel(
            name='FiniSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [ru]')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [en]')),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 [kz]')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [ru]')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [en]')),
                ('alt_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xb4\xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb0 [kz]')),
                ('orderby', models.IntegerField(default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xb5 \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
                ('isvisible', models.BooleanField(default=False, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb7\xd0\xb8\xd1\x82\xd1\x8c')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\xa1\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('kase_info_key', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xd0\x9a\xd0\xbb\xd1\x8e\xd1\x87')),
            ],
            options={
                'ordering': ['orderby', 'pk'],
                'db_table': 'fini_section',
            },
        ),
        migrations.AddField(
            model_name='finicode',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.FiniSection'),
        ),
    ]
