# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finicode',
            options={'ordering': ['fini_code_so', 'pk'], 'permissions': (('view_indicators', 'Can view indicators'), ('edit_indicator', 'Can edit indicator'))},
        ),
        migrations.AlterModelOptions(
            name='finisection',
            options={'ordering': ['orderby', 'pk'], 'permissions': (('edit_section_of_indicators', 'Can edit section of indicators'),)},
        ),
    ]
