# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentclosure_parents', to='documents.Document')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentclosure_children', to='documents.Document')),
            ],
            options={
                'db_table': 'kase_tree_docsclosure',
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentclosure',
            unique_together=set([('parent', 'child')]),
        ),
    ]
