# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20171205_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['idx', 'pk'], 'permissions': (('view_slide', 'Can view slides'), ('view_slide_change_history', 'Can view change history of the slide'))},
        ),
    ]
