# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('head_ru', models.CharField(max_length=200, null=True, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('head_en', models.CharField(max_length=200, null=True, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('head_kz', models.CharField(max_length=200, null=True, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('body', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('body_kz', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('link', models.URLField(verbose_name=b'C\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('link_ru', models.URLField(null=True, verbose_name=b'C\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('link_en', models.URLField(null=True, verbose_name=b'C\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('link_kz', models.URLField(null=True, verbose_name=b'C\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('category_id', models.IntegerField(choices=[(1, b'\xd0\xa4\xd0\xbe\xd0\xbd\xd0\xb4\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd1\x80\xd1\x8b\xd0\xbd\xd0\xbe\xd0\xba \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81 PRO')], verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f')),
                ('idx', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd0\xb5 \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb8')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['idx', 'pk'],
                'db_table': 'kase_video',
                'permissions': (('view_video', 'Can view videos'),),
            },
        ),
    ]
